#https://github.com/nischalstha9/NginxLogExporter
version: "3"
services:
  nginx_exporter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./var/log/nginx:/code/src/NginxExporterLogStorage
      - ./exporter-data/seek_index:/code/src/exporter-data

    
  